version: '3.7'

services:
  microservice:
    build:
      context: .
    image: lreimer/realistic-cloud-native-devel
    ports:
      - "8080:8080"
    deploy:
      replicas: 2

  hoverfly:
    image: "spectolabs/hoverfly:v1.1.4"
    command: -import /simulations/weather.json
    volumes:
      - ./src/test/resources/hoverfly:/simulations
    ports:
      - "8888:8888"
      - "8500:8500"

  database:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    ports:
      - "3306:3306"
