---
apiVersion: v1
kind: Service
metadata:
  labels:
    tier: backend
    io.kompose.service: microservice
  name: microservice
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: microservice
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: microservice
  name: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: microservice
      tier: backend
  template:
    metadata:
      labels:
        io.kompose.service: microservice
        tier: backend
    spec:
      containers:
        - image: lreimer/realistic-cloud-native-devel
          imagePullPolicy: "IfNotPresent"
          name: microservice
          ports:
            - containerPort: 8080
